

** Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:
Download from https://github.com/ok/notmuch-webui

** Usage
:PROPERTIES:
:CUSTOM_ID: usage
:END:
FIXME: explanation

Run the project directly, via =:exec-fn=:

#+begin_example
$ clojure -X:run-x
Hello, Clojure!
#+end_example

Run the project, overriding the name to be greeted:

#+begin_example
$ clojure -X:run-x :name '"Someone"'
Hello, Someone!
#+end_example

Run the project directly, via =:main-opts= (=-m ok.notmuch-webui=):

#+begin_example
$ clojure -M:run-m
Hello, World!
#+end_example

Run the project, overriding the name to be greeted:

#+begin_example
$ clojure -M:run-m Via-Main
Hello, Via-Main!
#+end_example

Run the project's tests (they'll fail until you edit them):

#+begin_example
$ clojure -T:build test
#+end_example

Run the project's CI pipeline and build an uberjar (this will fail until
you edit the tests to pass):

#+begin_example
$ clojure -T:build ci
#+end_example

Run that uberjar:

#+begin_example
$ java -jar target/notmuch-webui-0.1.0-SNAPSHOT.jar
#+end_example

** Options
:PROPERTIES:
:CUSTOM_ID: options
:END:
FIXME: listing of options this app accepts.

** Examples
:PROPERTIES:
:CUSTOM_ID: examples
:END:
...

*** Bugs
:PROPERTIES:
:CUSTOM_ID: bugs
:END:
...

*** Any Other Sections
:PROPERTIES:
:CUSTOM_ID: any-other-sections
:END:
*** That You Think
:PROPERTIES:
:CUSTOM_ID: that-you-think
:END:
*** Might be Useful
:PROPERTIES:
:CUSTOM_ID: might-be-useful
:END:
** Implementaion plan
*** Maybe Next
**** IDEA jetty9?
     :LOGBOOK:
     - State "IDEA"       from              [2025-03-02 Sun 11:20]
     :END:

     What is this and does it provide any additional benifit?
     - [ ] maybe use https://github.com/sunng87/ring-jetty9-adapter ?

**** NEXT logging?
     :LOGBOOK:
     - State "NEXT"       from              [2025-03-02 Sun 11:15]
     :END:

     #+begin_example
     ;; Notes on logging: https://gist.github.com/jacobobryant/76b7a08a07d5ef2cc076b048d078f1f3
     org.slf4j/slf4j-simple     {:mvn/version "2.0.0-alpha5"}
     org.slf4j/log4j-over-slf4j {:mvn/version "1.7.36"}
     org.slf4j/jul-to-slf4j     {:mvn/version "1.7.36"}
     org.slf4j/jcl-over-slf4j   {:mvn/version "1.7.36"}
     #+end_example

*** Bootstraping plan of [2025-03-02 Sun] [66%]
**** DONE web server/jetty start
     CLOSED: [2025-03-02 Sun 11:10]
     :LOGBOOK:
     - State "DONE"       from              [2025-03-02 Sun 11:10]
     :END:
**** DONE cider-nrepl
     CLOSED: [2025-03-02 Sun 11:10]
     :LOGBOOK:
     - State "DONE"       from "TODO"       [2025-03-02 Sun 11:10]
     - State "TODO"       from              [2025-03-02 Sun 11:10]
     :END:
**** DONE How to reload code during development?
     CLOSED: [2025-03-02 Sun 11:00]
     :LOGBOOK:
     - State "DONE"       from "TODO"       [2025-03-02 Sun 11:00]
     - State "TODO"       from              [2025-03-02 Sun 10:55]
     :END:

     Following this advice:
     https://tonitalksdev.com/clojure-ring-hot-reload-server-on-code-changes -- Works!

**** DONE Dev server reload on save
     CLOSED: [2025-03-02 Sun 11:10]
     :LOGBOOK:
     - State "DONE"       from              [2025-03-02 Sun 11:10]
     :END:
**** DONE routing
     CLOSED: [2025-03-02 Sun 11:10]
     :LOGBOOK:
     - State "DONE"       from              [2025-03-02 Sun 11:10]
     :END:

**** DONE Selmer
     CLOSED: [2025-03-02 Sun 14:45]
     :LOGBOOK:
     - State "DONE"       from "WORKING"    [2025-03-02 Sun 14:45]
     CLOCK: [2025-03-02 Sun 14:38]--[2025-03-02 Sun 14:46] =>  0:08
     - State "WORKING"    from "TODO"       [2025-03-02 Sun 11:55]
     - State "TODO"       from              [2025-03-02 Sun 11:10]
     :END:

**** WORKING data-star [2/3]
     :LOGBOOK:
     - State "WORKING"    from "TODO"       [2025-03-02 Sun 11:20]
     CLOCK: [2025-03-02 Sun 11:18]--[2025-03-02 Sun 11:55] =>  0:37
     - State "TODO"       from              [2025-03-02 Sun 11:10]
     :END:

 - [X] Frontend / code / package
 - [X] Rendering static
 - [ ] Backend

**** TODO Bulma CSS
     :LOGBOOK:
     - State "TODO"       from              [2025-03-02 Sun 11:10]
     :END:

**** TODO Auto-running tests during development
     :LOGBOOK:
     - State "TODO"       from              [2025-03-02 Sun 11:10]
     :END:

**** Unsorted


** License
:PROPERTIES:
:CUSTOM_ID: license
:END:
Copyright © 2025 Oleksii

/EPLv1.0 is just the default for projects generated by =clj-new=: you
are not/ /required to open source this project, nor are you required to
use EPLv1.0!/ /Feel free to remove or change the =LICENSE= file and
remove or update this/ /section of the =README.md= file!/

Distributed under the Eclipse Public License version 1.0.
